services:
  webapp:
    build: .
    container_name: mcskript-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app # 🔹 Lokale Dateien in den Container mounten
      - /app/node_modules # 🔹 Verhindert Konflikte mit Node Modules
    environment:
      - HOST=0.0.0.0
    networks:
      - express_network

networks:
  express_network:
    external: true
